### ISSUE TITLE
Can't add location resource when I'm an admin and created the project

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#743]
### Steps to reproduce the error

- Add location to a project that you are an administrator of
- Attempt to add a location to that project

### Actual behavior

- Getting a permission denied erro

### Expected behavior

- Expect to be able to perform action because I'm an administrator of the project and created the location  (plus I'm also logged in as a superuser)

Screenshot of errror:
![screenshot 2016-09-28 13 07 29](https://cloud.githubusercontent.com/assets/1119621/18926285/d595b450-857c-11e6-9e73-2cc6bd3c169f.png)

Screenshot of permissions for user for the project:

![screenshot 2016-09-28 13 06 48](https://cloud.githubusercontent.com/assets/1119621/18926298/e5c37eac-857c-11e6-90fd-19ec7b4767f4.png)

**Comment by manoramahp** [comment]
@clash99 I've noticed the following behavior when I tried to attach a resource to a location.

When there are no resources attached to the projects, I'm getting the permission denied error.
But when I add a resource to the project and then tried to attach a resource to a location, I'm not getting such error and I could attach the resource.

**Comment by kavindya89** [comment]
@clash99 There is slight permission issue which is mentioned in https://github.com/Cadasta/cadasta-platform/issues/754. I have fixed it in https://github.com/Cadasta/cadasta-platform/pull/757. This issue might go away with it.

**Comment by kavindya89** [comment]
@clash99 i have checked the scenario with the fix. It's working fine.

**Comment by dpalomino** [comment]
@clash99 

I think this the same issue as #754. I've doing some testing and seen that: 

- If there are no resources in the library, then user cannot add location resources
- But if there are any resources in the library, then you can attach them to the location (but still not uploading a new file)

**Comment by clash99** [comment]
@kavindya89 and @dpalomino - Sounds like it is all related to #754 so once that fix is merged, we can do a final verification and consider this one closed.  Thanks again.

**Comment by kavindya89** [comment]
@clash99 @dpalomino yes I have checked both the cases with the fix. It's works fine. Once the pull request is merged. We can close both the tickets

**Comment by seav** [comment]
Fixed via #757.
